@startuml C4_Component_UserService
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов - Сервис управления пользователями

Container(api_gateway, "API Gateway", "Go/Gin", "Маршрутизирует запросы")
Container(auth_service, "Сервис аутентификации", "Go", "Управляет аутентификацией пользователей")
ContainerDb(database, "База данных", "PostgreSQL", "Хранение данных пользователей")

Container_Boundary(user_service, "Сервис управления пользователями") {
    Component(user_api, "User API", "REST/gRPC", "API для управления пользователями")
    Component(user_manager, "Менеджер пользователей", "Go", "Логика управления пользователями")
    Component(data_access, "Репозиторий", "Go", "Абстракция для работы с БД")
}

Rel(api_gateway, user_api, "Запросы управления пользователями", "gRPC")

Rel(user_api, user_manager, "Операции создания и редактирования пользователей", "")

Rel(user_manager, auth_service, "Создание учетных записей", "gRPC")
Rel(user_manager, data_access, "Сохранение пользователей в БД", "gRPC")

Rel(data_access, database, "SQL запросы", "SQL")

SHOW_LEGEND()
@enduml