@startuml ER_Diagram

entity "User" {
  * id : int
  --
  * name : string
  * login : string
  * password_sha256 : string
  * role : string
}

entity "Device" {
  * id : int
  --
  * name : string
  * type : string
  * protocol : string
  * uri : string
  * settings : string
  + user_id : int
}

entity "Sensor" {
  * id : int
  --
  * update_frequency : int
  * last_updated_ts : int
  * last_state : string
  + device_id : int
}

entity "Action" {
  * id : int
  --
  * type : string
  + device_id : int
}

entity "Trigger" {
  * id : int
  --
  * type : string
  * threshold : int
  * operator : string
  + sensor_id : int
  + action_id : int
}

User ||--o{ Device : "owns"
Device ||--o{ Sensor : "has"
Device ||--o{ Action : "has"
Sensor ||--o{ Trigger : "triggers"
Action ||--o{ Trigger : "triggered by"

@enduml